<a href="https://colab.research.google.com/github/ocalvp00/Lab2/blob/main/Exercise10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

array = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])

column = np.array([[10, 10, 10]])

print("Printing Original array")
print(array)

array_deleted = np.delete(array, 1, axis=1)
print("\nArray after deleting column 2")
print(array_deleted)

array_inserted = np.insert(array_deleted, 1, column, axis=1)
print("\nArray after inserting column 2")
print(array_inserted)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Array after deleting column 2
[[34 73]
 [82 12]
 [53 66]]

Array after inserting column 2
[[34 10 73]
 [82 10 12]
 [53 10 66]]
