<a href="https://colab.research.google.com/github/ocalvp00/Lab2/blob/main/Exercise9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

array = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])

#Case 1
print("Printing Original array")
print(array)

index_row = np.argsort(array[1, :])

array_row = array[:, index_row]
print("\nSorting Original array by second row")
print(array_row)


#Case 2
index_column = np.argsort(array[:, 1])

array_column = array[index_column, :]
print("\nSorting Original array by second column")
print(array_column)


Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Sorting Original array by second row
[[73 43 34]
 [12 22 82]
 [66 94 53]]

Sorting Original array by second column
[[82 22 12]
 [34 43 73]
 [53 94 66]]
